# Zajednička konfiguracija za sve karte troška
# (globalnu i lokalnu)

# Poligon koji opisuje vanjske dimenzije vozila.
# Mjerne jedinice su metri.
footprint: [[-0.225, -0.145], [0.125, -0.145], [0.125, 0.145], [-0.225, 0.145]]

# Tipovi podataka uključeni u karte troška.
# U ovom slučaju to su prepreke i "Inflation layer"
# koji predstavlja sigurnosnu zonu oko prepreka.
plugins: 
  - {name: obstacle_layer,       type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer,        type: "costmap_2d::InflationLayer"}

obstacle_layer:
  # Senzori koji se koriste za osvježavanje karte troška
  observation_sources: laser_scan_sensor
  # Parametri laserskog senzora koji se koristi za osvježavanje karte troška
  laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: laser/scan, marking: true, clearing: true}
  # Prepreke udaljenije od obstacle_range
  # neće biti uzete u obzir
  obstacle_range: 2.5
  # Maksimalna udaljenost do koje čistimo
  # karte troška na temelju očitanja senzora
  raytrace_range: 3.0

inflation_layer:
  # Sve planirane putanje koje su od prepreke udaljene
  # više od vrijednosti inflation_radius imaju jednak trošak
  inflation_radius: 0.55
